namespace com.InnovaMD.Provider.Models.SystemConfiguration
{
    public static class  ConfigurationConstants
    {
        //TODO Remove if not necesary
        public const string DEFAULT_STATE_ID = "DEFAULT_STATE_ID";
        public const string CLINICAL_CONSULTATION_HISTORY_SEARCH_PAGE_SIZE = "CLINICAL_CONSULTATION_HISTORY_SEARCH_PAGE_SIZE";
        //Create Button for Specialist
        public const string CREATE_CONSULTATION_PROVIDER_SPECIALIST_STARTDATE = "CREATE_CONSULTATION_PROVIDER_SPECIALIST_STARTDATE";
        public const string CREATE_CONSULTATION_PROVIDER_SPECIALIST_ENDDATE = "CREATE_CONSULTATION_PROVIDER_SPECIALIST_ENDDATE";
        public const string CREATE_CONSULTATION_PROVIDER_SPECIALIST_MESSAGE = "CREATE_CONSULTATION_PROVIDER_SPECIALIST_MESSAGE";
        //Create Button for PCP
        public const string CREATE_CONSULTATION_PROVIDER_PCP_STARTDATE = "CREATE_CONSULTATION_PROVIDER_PCP_STARTDATE";
        public const string CREATE_CONSULTATION_PROVIDER_PCP_ENDDATE = "CREATE_CONSULTATION_PROVIDER_PCP_ENDDATE";
        public const string CREATE_CONSULTATION_PROVIDER_PCP_MESSAGE = "CREATE_CONSULTATION_PROVIDER_PCP_MESSAGE";
        //Create Button for IPA
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_IPA_STARTDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_IPA_STARTDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_IPA_ENDDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_IPA_ENDDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_IPA_MESSAGE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_IPA_MESSAGE";
        //Create Button for SIPA
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_SIPA_STARTDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_SIPA_STARTDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_SIPA_ENDDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_SIPA_ENDDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_SIPA_MESSAGE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_SIPA_MESSAGE";
        //Create Button for PMG
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_PMG_STARTDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_PMG_STARTDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_PMG_ENDDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_PMG_ENDDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_PMG_MESSAGE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_PMG_MESSAGE";
        //Create Button for SPMG
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_SPMG_STARTDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_SPMG_STARTDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_SPMG_ENDDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_SPMG_ENDDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_SPMG_MESSAGE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_SPMG_MESSAGE";
        //Create Button for MSO
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_MSO_STARTDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_MSO_STARTDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_MSO_ENDDATE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_MSO_ENDDATE";
        public const string CREATE_CONSULTATION_ADMINISTRATIONGROUP_MSO_MESSAGE = "CREATE_CONSULTATION_ADMINISTRATIONGROUP_MSO_MESSAGE";
        //Create Button for GROUP_PRACTICE
        public const string CREATE_CONSULTATION_PROVIDER_GROUP_PRACTICE_STARTDATE = "CREATE_CONSULTATION_PROVIDER_GROUP_PRACTICE_STARTDATE";
        public const string CREATE_CONSULTATION_PROVIDER_GROUP_PRACTICE_ENDDATE = "CREATE_CONSULTATION_PROVIDER_GROUP_PRACTICE_ENDDATE";
        public const string CREATE_CONSULTATION_PROVIDER_GROUP_PRACTICE_MESSAGE = "CREATE_CONSULTATION_PROVIDER_GROUP_PRACTICE_MESSAGE";
        //Create Button for ANCILLARY
        public const string CREATE_CONSULTATION_PROVIDER_ANCILLARY_STARTDATE = "CREATE_CONSULTATION_PROVIDER_ANCILLARY_STARTDATE";
        public const string CREATE_CONSULTATION_PROVIDER_ANCILLARY_ENDDATE = "CREATE_CONSULTATION_PROVIDER_ANCILLARY_ENDDATE";
        public const string CREATE_CONSULTATION_PROVIDER_ANCILLARY_MESSAGE = "CREATE_CONSULTATION_PROVIDER_ANCILLARY_MESSAGE";
        //Create Button for HOSPITAL
        public const string CREATE_CONSULTATION_PROVIDER_HOSPITAL_STARTDATE = "CREATE_CONSULTATION_PROVIDER_HOSPITAL_STARTDATE";
        public const string CREATE_CONSULTATION_PROVIDER_HOSPITAL_ENDDATE = "CREATE_CONSULTATION_PROVIDER_HOSPITAL_ENDDATE";
        public const string CREATE_CONSULTATION_PROVIDER_HOSPITAL_MESSAGE = "CREATE_CONSULTATION_PROVIDER_HOSPITAL_MESSAGE";
        //Create Button for PHARMACY
        public const string CREATE_CONSULTATION_PROVIDER_PHARMACY_STARTDATE = "CREATE_CONSULTATION_PROVIDER_PHARMACY_STARTDATE";
        public const string CREATE_CONSULTATION_PROVIDER_PHARMACY_ENDDATE = "CREATE_CONSULTATION_PROVIDER_PHARMACY_ENDDATE";
        public const string CREATE_CONSULTATION_PROVIDER_PHARMACY_MESSAGE = "CREATE_CONSULTATION_PROVIDER_PHARMACY_MESSAGE";
        //Create Button for DENTAL
        public const string CREATE_CONSULTATION_PROVIDER_DENTAL_STARTDATE = "CREATE_CONSULTATION_PROVIDER_DENTAL_STARTDATE";
        public const string CREATE_CONSULTATION_PROVIDER_DENTAL_ENDDATE = "CREATE_CONSULTATION_PROVIDER_DENTAL_ENDDATE";
        public const string CREATE_CONSULTATION_PROVIDER_DENTAL_MESSAGE = "CREATE_CONSULTATION_PROVIDER_DENTAL_MESSAGE";
        //Create Button for MENTAL_HEALTH_CARE
        public const string CREATE_CONSULTATION_PROVIDER_MENTAL_HEALTH_CARE_STARTDATE = "CREATE_CONSULTATION_PROVIDER_MENTAL_HEALTH_CARE_STARTDATE";
        public const string CREATE_CONSULTATION_PROVIDER_MENTAL_HEALTH_CARE_ENDDATE = "CREATE_CONSULTATION_PROVIDER_MENTAL_HEALTH_CARE_ENDDATE";
        public const string CREATE_CONSULTATION_PROVIDER_MENTAL_HEALTH_CARE_MESSAGE = "CREATE_CONSULTATION_PROVIDER_MENTAL_HEALTH_CARE_MESSAGE";
        //Create Button for CAMP
        public const string CREATE_CONSULTATION_PROVIDER_CAMP_STARTDATE = "CREATE_CONSULTATION_PROVIDER_CAMP_STARTDATE";
        public const string CREATE_CONSULTATION_PROVIDER_CAMP_ENDDATE = "CREATE_CONSULTATION_PROVIDER_CAMP_ENDDATE";
        public const string CREATE_CONSULTATION_PROVIDER_CAMP_MESSAGE = "CREATE_CONSULTATION_PROVIDER_CAMP_MESSAGE";
        //Create Button for Specialist
        public const string CREATE_CONSULTATION_PAYER_REPRESENTATIVE_STARTDATE = "CREATE_CONSULTATION_PAYER_REPRESENTATIVE_STARTDATE";
        public const string CREATE_CONSULTATION_PAYER_REPRESENTATIVE_ENDDATE = "CREATE_CONSULTATION_PAYER_REPRESENTATIVE_ENDDATE";
        public const string CREATE_CONSULTATION_PAYER_REPRESENTATIVE_MESSAGE = "CREATE_CONSULTATION_PAYER_REPRESENTATIVE_MESSAGE";

        public const string POWERBI_REPORTS_AUTHORITY = "POWERBI_REPORTS_AUTHORITY";
        public const string POWERBI_REPORTS_RESOURCE = "POWERBI_REPORTS_RESOURCE";
        public const string POWERBI_REPORTS_CLIENT_IDENTIFIER = "POWERBI_REPORTS_CLIENT_IDENTIFIER";
        public const string POWERBI_REPORTS_CLIENT_SECRET = "POWERBI_REPORTS_CLIENT_SECRET";
        public const string POWERBI_REPORTS_API_BASEURL = "POWERBI_REPORTS_API_BASEURL";
        public const string POWERBI_REPORTS_RETRY_AFTER = "POWERBI_REPORTS_RETRY_AFTER";

        public const string PORTAL_CLINICAL_CONSULTATION_REPORT_GROUP_ID = "PORTAL_CLINICAL_CONSULTATION_REPORT_GROUP_ID";
        public const string PORTAL_CLINICAL_CONSULTATION_REPORT_ID = "PORTAL_CLINICAL_CONSULTATION_REPORT_ID";
        public const string PORTAL_CLINICAL_CONSULTATION_REPORT_EXPORT_TIMEOUT = "PORTAL_CLINICAL_CONSULTATION_REPORT_EXPORT_TIMEOUT";
        public const string PORTAL_CLINICAL_CONSULTATION_REPORT_EXPORT_FILENAME = "PORTAL_CLINICAL_CONSULTATION_REPORT_EXPORT_FILENAME";

        public const string REFERRALS_DISCLAIMER_MESSAGE = "REFERRALS_DISCLAIMER_MESSAGE";
        public const string REFERRALS_SHOW_DISCLAIMER_PRINT = "REFERRALS_SHOW_DISCLAIMER_PRINT";

        public const string SEARCH_REQUESTING_PROVIDER_PAGE_SIZE = "SEARCH_REQUESTING_PROVIDER_PAGE_SIZE";
        public const string CANCEL_CREATE_CONSULTATION_MESSAGE = "CANCEL_CREATE_CONSULTATION_MESSAGE";

        public const string CREATE_DISABLED_GLOBAL_MESSAGE = "CREATE_DISABLED_GLOBAL_MESSAGE";
        public const string MAX_NUMBER_OF_RECENT_DIAGNOSES = "MAX_NUMBER_OF_RECENT_DIAGNOSES";
        public const string SEARCH_DIAGNOSIS_PAGE_SIZE = "SEARCH_DIAGNOSIS_PAGE_SIZE";
        public const string ALLOW_PROCEDURE_BUNDLE_AUTO_SELECT = "ALLOW_PROCEDURE_BUNDLE_AUTO_SELECT";
        public const string NO_PCP_MESSAGE = "NO_PCP_MESSAGE";
        public const string SERVICE_QUANTITY_MAXIMUM = "SERVICE_QUANTITY_MAXIMUM";
        public const string SERVICE_QUANTITY_REQUIRED = "SERVICE_QUANTITY_REQUIRED";
        public const string SERVICE_QUANTITY_MINIMUM = "SERVICE_QUANTITY_MINIMUM";
        public const string CREATE_CONSULTATION_COMPLETE_STEPS_VALIDATION_MSG = "CREATE_CONSULTATION_COMPLETE_STEPS_VALIDATION_MSG";
        public const string SEARCH_SERVICING_PROVIDER_PAGE_SIZE = "SEARCH_SERVICING_PROVIDER_PAGE_SIZE";
        public const string CONSULTATION_DAYS_BACK_ALLOWED = "CONSULTATION_DAYS_BACK_ALLOWED";
        public const string REQUEST_CONSULTATION_MAXIMUM_ALLOWED_MESSAGE = "REQUEST_CONSULTATION_MAXIMUM_ALLOWED_MESSAGE";
        public const string REQUEST_CONSULTATION_MAXIMUM_ALLOWED_VALUE = "REQUEST_CONSULTATION_MAXIMUM_ALLOWED_VALUE";
        public const string RULES_OUT_MESSAGE = "RULES_OUT_MESSAGE";    
        public const string PPN_REASON = "PROVIDER_OUTSIDE_PPN_REASON_MESSAGE"; 
        public const string ADMINISTRATION_GROUP_TYPE = "ADMINISTRATION_GROUP_TYPE";
        public const string CREATE_CONSULTATION_SUBMIT_VALIDATION_MSG = "CREATE_CONSULTATION_SUBMIT_VALIDATION_MSG";
        public const string PROVIDER_PORTAL_CONSULTATION_EXPIRATION_DATE = "PROVIDER_PORTAL_CONSULTATION_EXPIRATION_DATE";
    }
}
